### ISSUE TITLE
手动安装依赖后依旧报错

### ISSUE THREAD

**Issue by Wind2009-Louse** [hemengke1997/vscode-image-manager#13]
```
[Image Manager] 🈶️ Activated, v0.14.1
[Image Manager] Dependencies Cache Dir: C:\Users\Nidhogg\.vscode-image-manager-cache
[Image Manager] Extension Root: c:\Users\Nidhogg\.vscode\extensions\minko.image-manager-0.14.1
[Image Manager] OS platform: win32-x64
[Image Manager] 🔄 Image Manager Initializing...
[Image Manager] Start manual install dependencies: libvips-8.14.5-win32-x64.tar.br
[Image Manager] Manual install success: libvips-8.14.5-win32-x64.tar.br
[Image Manager] 🐛 ERROR: Error: Command failed with exit code 1: node install/prebuild-install-bin.js
prebuild-install warn install read ECONNRESET
{
  "target": "14.17.3",
  "runtime": "node",
  "arch": "x64",
  "libc": "",
  "platform": "win32",
  "debug": false,
  "force": false,
  "verbose": false,
  "buildFromSource": true,
  "path": "c:\\Users\\Nidhogg\\.vscode\\extensions\\minko.image-manager-0.14.1\\dist\\lib",
  "local-prebuilds": "prebuilds",
  "tag-prefix": "v",
  "_": [
    "D:\\Program Files\\nodejs\\node.exe",
    "c:\\Users\\Nidhogg\\.vscode\\extensions\\minko.image-manager-0.14.1\\dist\\lib\\install\\prebuild-install-bin.js"
  ],
  "abi": "83"
}
Error: Command failed with exit code 1: node install/prebuild-install-bin.js
prebuild-install warn install read ECONNRESET
{
  "target": "14.17.3",
  "runtime": "node",
  "arch": "x64",
  "libc": "",
  "platform": "win32",
  "debug": false,
  "force": false,
  "verbose": false,
  "buildFromSource": true,
  "path": "c:\\Users\\Nidhogg\\.vscode\\extensions\\minko.image-manager-0.14.1\\dist\\lib",
  "local-prebuilds": "prebuilds",
  "tag-prefix": "v",
  "_": [
    "D:\\Program Files\\nodejs\\node.exe",
    "c:\\Users\\Nidhogg\\.vscode\\extensions\\minko.image-manager-0.14.1\\dist\\lib\\install\\prebuild-install-bin.js"
  ],
  "abi": "83"
}
    at sp (c:\Users\Nidhogg\.vscode\extensions\minko.image-manager-0.14.1\dist\extension.js:314:57)
    at c:\Users\Nidhogg\.vscode\extensions\minko.image-manager-0.14.1\dist\extension.js:315:1360
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Vg._install (c:\Users\Nidhogg\.vscode\extensions\minko.image-manager-0.14.1\dist\extension.js:318:4931)
    at Vg._showStausBar (c:\Users\Nidhogg\.vscode\extensions\minko.image-manager-0.14.1\dist\extension.js:318:2160)
    at Vg.run (c:\Users\Nidhogg\.vscode\extensions\minko.image-manager-0.14.1\dist\extension.js:318:766)
    at Function.installSharp (c:\Users\Nidhogg\.vscode\extensions\minko.image-manager-0.14.1\dist\extension.js:338:9037)
    at Function.init (c:\Users\Nidhogg\.vscode\extensions\minko.image-manager-0.14.1\dist\extension.js:338:8044)
    at Rze (c:\Users\Nidhogg\.vscode\extensions\minko.image-manager-0.14.1\dist\extension.js:338:14143)
    at w.n (d:\Users\Nidhogg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6194)
    at w.m (d:\Users\Nidhogg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6157)
    at w.l (d:\Users\Nidhogg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:5614)
```

**Comment by hemengke1997** [comment]
初步判断还是网络原因导致的，资源在github上，没有下载下来。按理说你现在能上github，就能下载的
我这边需要对github上的资源做一下处理，如果你可以翻墙的话，翻墙后再尝试一下自动安装，若不行的话就稍等我之后处理这个问题

**Comment by Wind2009-Louse** [comment]
我这边网络环境是可以直连github的
重试几次，有时会报TIMEOUT 20.205.243.166

**Comment by hemengke1997** [comment]
fixed in `v0.15.0`, 请升级到最新版后重新启动vscode尝试，谢谢
