### ISSUE TITLE
昨天正常使用，今天使用时报错Dependencies install failed

### ISSUE THREAD

**Issue by Wind2009-Louse** [hemengke1997/vscode-image-manager#19]
[Image Manager] Tip: The following is the manual download dependencies address, if the automatic installation of dependencies fails, please follow the documentation to manually download the following dependencies ⬇️
[Image Manager] https://registry.npmmirror.com/-/binary/sharp-libvips/v8.15.2/libvips-8.15.2-win32-x64.tar.gz
[Image Manager] 🔄 Image Manager Initializing...
[Image Manager] libvips Start auto install dependencies
[Image Manager] 🐛 ERROR: Error: Command failed with exit code 1: D:\Users\AppData\Local\Programs\Microsoft VS Code\Code.exe install/install-libvips.js
sharp: Installation error: Prebuilt libvips 8.15.2 binaries are not yet available for win32-x64
sharp: Downloading https://registry.npmmirror.com/-/binary/sharp-libvips/sharp-libvips/v8.15.2/libvips-8.15.2-win32-x64.tar.gz
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
Error: Command failed with exit code 1: D:\Users\AppData\Local\Programs\Microsoft VS Code\Code.exe install/install-libvips.js
sharp: Installation error: Prebuilt libvips 8.15.2 binaries are not yet available for win32-x64
sharp: Downloading https://registry.npmmirror.com/-/binary/sharp-libvips/sharp-libvips/v8.15.2/libvips-8.15.2-win32-x64.tar.gz
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
    at ap (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:317:57)
    at c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:1360
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Hg._install (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:9269)
    at Hg._showStausBar (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:6098)
    at Hg.run (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:4450)
    at Function.installSharp (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:9705)
    at Function.init (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:8674)
    at U9e (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:14921)
    at w.n (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6194)
    at w.m (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6157)
    at w.l (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:5614)
[Image Manager] 🐛 ERROR: Error: Command failed with exit code 1: D:\Users\AppData\Local\Programs\Microsoft VS Code\Code.exe install/dll-copy.js
sharp: Installation error: ENOENT: no such file or directory, scandir 'c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\vendor\8.15.2\win32-x64\lib'
sharp: Creating c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\build\Release
sharp: Copying DLLs from c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\vendor\8.15.2\win32-x64\lib to c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\build\Release
Error: Command failed with exit code 1: D:\Users\AppData\Local\Programs\Microsoft VS Code\Code.exe install/dll-copy.js
sharp: Installation error: ENOENT: no such file or directory, scandir 'c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\vendor\8.15.2\win32-x64\lib'
sharp: Creating c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\build\Release
sharp: Copying DLLs from c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\vendor\8.15.2\win32-x64\lib to c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\build\Release
    at ap (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:317:57)
    at c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:1360
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Hg._install (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:9604)
    at Hg._showStausBar (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:6098)
    at Hg.run (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:4450)
    at Function.installSharp (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:9705)
    at Function.init (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:8674)
    at U9e (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:14921)
    at w.n (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6194)
    at w.m (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6157)
    at w.l (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:5614)

**Comment by hemengke1997** [comment]
谢谢反馈，昨天进行了一次大更新，造成了不稳定。请先安装 0.24.0，我会尽快修复此问题

**Comment by hemengke1997** [comment]
麻烦你开启 `image-manager.debug.enabled: true`，再复制一下打印我排查问题

**Comment by Wind2009-Louse** [comment]
```
[Image Manager] Activated, v1.0.0
[Image Manager] [i18n] language: en
[Image Manager] Dependencies Cache Dir: C:\Users\.vscode-image-manager-cache
[Image Manager] Extension Root: c:\Users\.vscode\extensions\minko.image-manager-1.0.0
[Image Manager] Tip: The following is the manual download dependencies address, if the automatic installation of dependencies fails, please follow the documentation to manually download the following dependencies ⬇️
[Image Manager] https://registry.npmmirror.com/-/binary/sharp-libvips/v8.15.2/libvips-8.15.2-win32-x64.tar.gz
[Image Manager] 🔄 Image Manager Initializing...
[Image Manager] [DEBUG]: useMirror: true
[Image Manager] [DEBUG]: extensionHost: c:\Users\.vscode\extensions\minko.image-manager-1.0.0
[Image Manager] [DEBUG]: sharpBinaryReleaseDir: c:\Users\.vscode\extensions\minko.image-manager-1.0.0\releases
[Image Manager] libvips Start auto install dependencies
[Image Manager] [DEBUG]: npm_config_sharp_libvips_binary_host: https://registry.npmmirror.com/-/binary/sharp-libvips/sharp-libvips
[Image Manager] 🐛 ERROR: Error: Command failed with exit code 1: D:\Users\AppData\Local\Programs\Microsoft VS Code\Code.exe install/install-libvips.js
sharp: Installation error: Prebuilt libvips 8.15.2 binaries are not yet available for win32-x64
sharp: Downloading https://registry.npmmirror.com/-/binary/sharp-libvips/sharp-libvips/v8.15.2/libvips-8.15.2-win32-x64.tar.gz
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
Error: Command failed with exit code 1: D:\Users\AppData\Local\Programs\Microsoft VS Code\Code.exe install/install-libvips.js
sharp: Installation error: Prebuilt libvips 8.15.2 binaries are not yet available for win32-x64
sharp: Downloading https://registry.npmmirror.com/-/binary/sharp-libvips/sharp-libvips/v8.15.2/libvips-8.15.2-win32-x64.tar.gz
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
    at ap (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:317:57)
    at c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:1360
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Hg._install (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:9269)
    at Hg._showStausBar (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:6098)
    at Hg.run (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:4450)
    at Function.installSharp (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:9705)
    at Function.init (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:8674)
    at U9e (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:14921)
    at w.n (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6194)
    at w.m (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6157)
    at w.l (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:5614)
[Image Manager] 🐛 ERROR: Error: Command failed with exit code 1: D:\Users\AppData\Local\Programs\Microsoft VS Code\Code.exe install/dll-copy.js
sharp: Installation error: ENOENT: no such file or directory, scandir 'c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\vendor\8.15.2\win32-x64\lib'
sharp: Creating c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\build\Release
sharp: Copying DLLs from c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\vendor\8.15.2\win32-x64\lib to c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\build\Release
Error: Command failed with exit code 1: D:\Users\AppData\Local\Programs\Microsoft VS Code\Code.exe install/dll-copy.js
sharp: Installation error: ENOENT: no such file or directory, scandir 'c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\vendor\8.15.2\win32-x64\lib'
sharp: Creating c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\build\Release
sharp: Copying DLLs from c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\vendor\8.15.2\win32-x64\lib to c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\lib\build\Release
    at ap (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:317:57)
    at c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:1360
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Hg._install (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:9604)
    at Hg._showStausBar (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:6098)
    at Hg.run (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:318:4450)
    at Function.installSharp (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:9705)
    at Function.init (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:8674)
    at U9e (c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist\extension.js:338:14921)
    at w.n (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6194)
    at w.m (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6157)
    at w.l (d:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:5614)
[Image Manager] [DEBUG]: htmlPath: c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist-webview\index.html
[Image Manager] [DEBUG]: htmlPath: c:\Users\.vscode\extensions\minko.image-manager-1.0.0\dist-webview\index.html
[Image Manager] [DEBUG]: Receive cmd: on_webview_ready
[Image Manager] [DEBUG]: Webview is ready
[Image Manager] [DEBUG]: Receive cmd: get_all_images
[Image Manager] [DEBUG]: Receive cmd: get_compressor
[Image Manager] [DEBUG]: Receive cmd: get_format_converter

```

**Comment by hemengke1997** [comment]
请升级到 v1.0.1，并重新选择镜像源url后重启vscode即可
